version: '3.8'
services:
  rctea-basic:
    image: iczpnet/letter-netcore-rctea-basic
    build:
      context: ../letter-netcore/
      dockerfile: host/IczpNet.IczpNet.RcteaBasic.HttpApi.Host/Dockerfile
    restart: unless-stopped
  nest-letter:
    image: iczpnet/letter-nest:v0.0.19
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rctea-basic
    ports:
      - '3005:3000'
    restart: unless-stopped
    environment:
      NODE_ENV: production
    env_file:
      - .env
