[edgedb]
server-version = "5.6"
# listen_addresses = ['10.0.5.20']

# [tool.edgedb.credentials.letter]
# user = "edgedb"
# database = "main"
# port = 10708
# password = "vpZbocFbvRXtSC2n4dMC4Zyq"
# tlsSecurity = "insecure"