// GENERATED by @edgedb/generate v0.5.5

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
export type $AuditLogλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "app_name": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "browser_info": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "client_id": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "client_name": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "handler_name": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "http_method": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "ip": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "url": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "user_id": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "user_name": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "duration": $.PropertyDesc<_std.$int64, $.Cardinality.AtMostOne, false, false, false, false>;
  "http_status": $.PropertyDesc<_std.$int64, $.Cardinality.AtMostOne, false, false, false, false>;
  "excution_time": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, true>;
  "data": $.PropertyDesc<_std.$json, $.Cardinality.AtMostOne, false, false, false, false>;
  "error": $.PropertyDesc<_std.$json, $.Cardinality.AtMostOne, false, false, false, false>;
  "headers": $.PropertyDesc<_std.$json, $.Cardinality.AtMostOne, false, false, false, false>;
  "host": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
}>;
type $AuditLog = $.ObjectType<"audit::AuditLog", $AuditLogλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $AuditLog = $.makeType<$AuditLog>(_.spec, "a5bd4ae2-6ce0-11ef-bbbe-d3da332b6cd4", _.syntax.literal);

const AuditLog: $.$expr_PathNode<$.TypeSet<$AuditLog, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($AuditLog, $.Cardinality.Many), null);



export { $AuditLog, AuditLog };

type __defaultExports = {
  "AuditLog": typeof AuditLog
};
const __defaultExports: __defaultExports = {
  "AuditLog": AuditLog
};
export default __defaultExports;
